version: "3.7"

networks:
  deployment:

services:
  app:
    image: ready1337g/pictures-by-breed:0.0.2
    networks:
      - deployment
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: preprod
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd
